apiVersion: v1
kind: MessagePlatformAdapter
metadata:
  name: lark
  label:
    en_US: Lark
    zh_CN: 飞书
  description:
    en_US: Lark Adapter
    zh_CN: 飞书适配器
spec:
  config:
    - name: app_id
      label:
        en_US: App ID
        zh_CN: 应用ID
      type: string
      required: true
      default: ""
    - name: app_secret
      label:
        en_US: App Secret
        zh_CN: 应用密钥
      type: string
      required: true
      default: ""
    - name: bot_name
      label:
        en_US: Bot Name
        zh_CN: 机器人名称
      type: string
      required: true
      default: ""
    - name: enable-webhook
      label:
        en_US: Enable Webhook Mode
        zh_CN: 启用Webhook模式
      type: boolean
      required: true
      default: false
    - name: port
      label:
        en_US: Webhook Port
        zh_CN: Webhook端口
      type: int
      required: true
      default: 2285
    - name: encrypt-key
      label:
        en_US: Encrypt Key
        zh_CN: 加密密钥
      type: string
      required: true
      default: ""
execution:
  python:
    path: ./lark.py
    attr: LarkAdapter