apiVersion: v1
kind: MessagePlatformAdapter
metadata:
  name: nakuru
  label:
    en_US: Nakuru
    zh_CN: Nakuru
  description:
    en_US: Nakuru Adapter
    zh_CN: Nakuru 适配器(go-cqhttp)
spec:
  config:
    - name: host
      label:
        en_US: Host
        zh_CN: 主机
      type: string
      required: true
      default: "127.0.0.1"
    - name: http_port
      label:
        en_US: HTTP Port
        zh_CN: HTTP端口
      type: int
      required: true
      default: 5700
    - name: ws_port
      label:
        en_US: WebSocket Port
        zh_CN: WebSocket端口
      type: int
      required: true
      default: 8080
    - name: token
      label:
        en_US: Token
        zh_CN: 令牌
      type: string
      required: true
      default: ""
execution:
  python:
    path: ./nakuru.py
    attr: NakuruAdapter
