apiVersion: v1
kind: MessagePlatformAdapter
metadata:
  name: officialaccount
  label:
    en_US: Official Account
    zh_CN: 微信公众号
  description:
    en_US: Official Account Adapter
    zh_CN: 微信公众号适配器
spec:
  config:
    - name: token
      label:
        en_US: Token
        zh_CN: 令牌
      type: string
      required: true
      default: ""
    - name: EncodingAESKey
      label:
        en_US: EncodingAESKey
        zh_CN: 消息加解密密钥
      type: string
      required: true
      default: ""
    - name: AppID
      label:
        en_US: App ID
        zh_CN: 应用ID
      type: string
      required: true
      default: ""
    - name: AppSecret
      label:
        en_US: App Secret
        zh_CN: 应用密钥
      type: string
      required: true
      default: ""
    - name: host
      label:
        en_US: Host
        zh_CN: 监听主机
      type: string
      required: true
      default: 0.0.0.0
    - name: port
      label:
        en_US: Port
        zh_CN: 监听端口
      type: int
      required: true
      default: 2287
execution:
  python:
    path: ./officialaccount.py
    attr: OfficialAccountAdapter
