apiVersion: v1
kind: MessagePlatformAdapter
metadata:
  name: wecom
  label:
    en_US: WeCom
    zh_CN: 企业微信
  description:
    en_US: WeCom Adapter
    zh_CN: 企业微信适配器
spec:
  config:
    - name: host
      label:
        en_US: Host
        zh_CN: 监听主机
      type: string
      required: true
      default: "0.0.0.0"
    - name: port
      label:
        en_US: Port
        zh_CN: 监听端口
      type: int
      required: true
      default: 2290
    - name: corpid
      label:
        en_US: Corpid
        zh_CN: 企业ID
      type: string
      required: true
      default: ""
    - name: secret
      label:
        en_US: Secret
        zh_CN: 密钥
      type: string
      required: true
      default: ""
    - name: token
      label:
        en_US: Token
        zh_CN: 令牌
      type: string
      required: true
      default: ""
    - name: EncodingAESKey
      label:
        en_US: EncodingAESKey
        zh_CN: 消息加解密密钥
      type: string
      required: true
      default: ""
    - name: contacts_secret
      label:
        en_US: Contacts Secret
        zh_CN: 通讯录密钥
      type: string
      required: true
      default: ""
execution:
  python:
    path: ./wecom.py
    attr: WecomAdapter
