apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: moonshot-chat-completions
  label:
    en_US: Moonshot
    zh_CN: 月之暗面
spec:
  config:
    - name: base-url
      label:
        en_US: Base URL
        zh_CN: 基础 URL
      type: string
      required: true
      default: "https://api.moonshot.com/v1"
    - name: args
      label:
        en_US: Args
        zh_CN: 附加参数
      type: object
      required: true
      default: {}
    - name: timeout
      label:
        en_US: Timeout
        zh_CN: 超时时间
      type: int
      required: true
      default: 120
execution:
  python:
    path: ./moonshotchatcmpl.py
    attr: MoonshotChatCompletions
