apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: ollama-chat
  label:
    en_US: Ollama
    zh_CN: Ollama
spec:
  config:
    - name: base-url
      label:
        en_US: Base URL
        zh_CN: 基础 URL
      type: string
      required: true
      default: "http://127.0.0.1:11434"
    - name: args
      label:
        en_US: Args
        zh_CN: 附加参数
      type: object
      required: true
      default: {}
    - name: timeout
      label:
        en_US: Timeout
        zh_CN: 超时时间
      type: int
      required: true
      default: 120
execution:
  python:
    path: ./ollamachat.py
    attr: OllamaChatCompletions
