apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: volcark-chat-completions
  label:
    en_US: Volc Engine Ark
    zh_CN: 火山方舟
spec:
  config:
    - name: base-url
      label:
        en_US: Base URL
        zh_CN: 基础 URL
      type: string
      required: true
      default: "https://ark.cn-beijing.volces.com/api/v3"
    - name: args
      label:
        en_US: Args
        zh_CN: 附加参数
      type: object
      required: true
      default: {}
    - name: timeout
      label:
        en_US: Timeout
        zh_CN: 超时时间
      type: int
      required: true
      default: 120
execution:
  python:
    path: ./volcarkchatcmpl.py
    attr: VolcArkChatCompletions
