admins: []
api:
    port: 5300
command:
    prefix:
    - '!'
    - ！
    privilege: {}
concurrency:
    pipeline: 20
    session: 1
mcp:
    servers: []
proxy:
    http: ''
    https: ''
system:
    jwt:
        expire: 604800
        secret: ''
